package p26to50

import common.runner

/** https://projecteuler.net/problem=45
  * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

  1533776805
  */

object problem045 extends runner {
  override def mainCase(): Any = {
    var limit = 1L
    var tri = Stream.from(286).map(n => n.toLong * (n + 1) / 2)
    var pen = Stream.from(166).map(n => n.toLong * (3 * n - 1) / 2)
    var hex = Stream.from(144).map(n => n.toLong * (2 * n - 1))
    do {
      limit = List(tri.head, pen.head, hex.head).max
      tri = tri.dropWhile(_ < limit)
      pen = pen.dropWhile(_ < limit)
      hex = hex.dropWhile(_ < limit)
    } while (tri.head != pen.head || tri.head != hex.head)
    (tri.head, pen.head, hex.head)
  }
}
